/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.0.0.0                                               */
/*  Date (dd.mm.yyyy): 29. 4.2020   Time (hh:mm): 18:55                        */
/*******************************************************************************/


#ifndef _SPEEDOMETER_VGA_LCD_RESOURCES_H_
#define _SPEEDOMETER_VGA_LCD_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define VGA_LCD 0
#define VGA_LCD_COLOR_FORMAT GX_COLOR_FORMAT_24XRGB
#define VGA_LCD_X_RESOLUTION 480
#define VGA_LCD_Y_RESOLUTION 272
#define VGA_LCD_THEME_1 0
#define VGA_LCD_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define VGA_LCD_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_RED 29
#define VGA_LCD_COLOR_TABLE_SIZE 30

/* Font ID definitions                                                         */

#define VGA_LCD_FONT_TABLE_SIZE 4

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_BACKGROUND 5
#define GX_PIXELMAP_ID_MS_AZURE_LOGO_SMALL 6
#define GX_PIXELMAP_ID_TACHOMETER_BACK 7
#define GX_PIXELMAP_ID_TACHOMETER_NEEDLE 8
#define VGA_LCD_PIXELMAP_TABLE_SIZE 9

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_1 1
#define GX_STRING_ID_MENU_1 2
#define GX_STRING_ID_MENU_2 3
#define GX_STRING_ID_MENU_3 4
#define GX_STRING_ID_CHINESE_1 5
#define GX_STRING_ID_CHINESE_2 6
#define VGA_LCD_STRING_TABLE_SIZE 7

#endif                                       /* sentry                         */
